### ISSUE TITLE
[feature request] Trinket Spyglass Compatibility

### ISSUE THREAD

**Issue by MinecraftGuy926** [joaoh1/OkZoomer#107]
I added a spyglass trinket slot but the "require spyglass" zoom option doesn't recognize that slot as my inventory.

Would be pretty cool if that could be remedied somehow

**Comment by EnnuiL** [comment]
Possible Trinkets bug? I could investigate a workaround that is compatible with Trinkets, but if the current code works with [Ennui's Bigger Inventories](https://github.com/EnnuiL/ennuis_bigger_inventories)? (this hasn't been tested) Then Trinkets ideally should work too

**Comment by EnnuiL** [comment]
I see what's going on: Ok Zoomer has to explicitly implement support for Trinkets because Trinkets' inventory is effectively a distinct world from Minecraft's inventory; oh well, I'll defer this to this mod's maintainer @UpcraftLP

**Comment by MinecraftGuy926** [comment]
thank you

**Comment by UpcraftLP** [comment]
Added in v9.1.0

**Comment by MinecraftGuy926** [comment]
Sweet! Would it be possible to add that feature to a 1.20.1 release?
