### ISSUE TITLE
Crash When Loading 4.0.0-beta.2 With Config From 4.0.0-alpha.4

### ISSUE THREAD

**Issue by mrgrim** [joaoh1/OkZoomer#11]
Deleting the config solved the issue. Unfortunately, in my haste, I did not save the config. Crash report attached.
[crash-2020-08-12_17.17.13-client.txt](https://github.com/joaoh1/OkZoomer/files/5065847/crash-2020-08-12_17.17.13-client.txt)

**Comment by joaoh1** [comment]
I'm aware of the issue, the 4.0.0alpha to 4.0.0beta config file converter will either be fixed or removed for the next release, the only solution for now is not having an okzoomer-next.json5 file in the config folder

**Comment by Madis0** [comment]
How about just renaming it like suffix "-old" instead of converting?

**Comment by joaoh1** [comment]
> How about just renaming it like suffix "-old" instead of converting?

Not a bad idea, I'll consider that

**Comment by joaoh1** [comment]
Fixed on 4.0.0-beta.3, the conversion now works properly, but only on Java 11+ due to issues, however, it won't crash anymore. On an unrelated note, the conversion leaves a backup for the old config file.
