### ISSUE TITLE
[Feature Request] Creative not needed spyglass mode but survival does mode

### ISSUE THREAD

**Issue by Disketaa** [joaoh1/OkZoomer#111]
I don't know if it a feature already, but I didn't find one. 
I want to use zoom without spyglass in creative / spectator but with in survival / adventure

**Comment by EnnuiL** [comment]
Partially addressed on Ok Zoomer 10.0.0-beta.1 by having Creative Mode bypass the zoom dependency; Spectator Mode is perhaps a bit more controversial and would need more thought (and maybe a whole system behind it)
