### ISSUE TITLE
OK Zoomer 10.0.0-beta.7 tagged Fabric API version does not exist

### ISSUE THREAD

**Issue by StarsShine11904** [joaoh1/OkZoomer#130]
The Fabric API version 0.106.0 marked by OK Zoomer 10.0.0-beta.7 in version 1.21 does not exist. Can this be fixed?

logs in [here](https://mclo.gs/Op3rZt7)

**Comment by UpcraftLP** [comment]
Hey, thanks for reporting! looks like during the latest feature backport that was copied from the wrong version by accident.
Will release a fixed version soon!

**Comment by StarsShine11904** [comment]
ok

**Comment by UpcraftLP** [comment]
Fixed in version `10.0.0-beta.8`
