### ISSUE TITLE
no okzoomer directory in assets folder

### ISSUE THREAD

**Issue by Bluesheep33** [joaoh1/OkZoomer#17]
I wanted to look for the okzoomer overlay in .minecraft but can't find assets/okzoomer/textures/misc/zoom_overlay.png

when going in .minecraft/assets i can't see an okzoomer folder

what am i doing wrong?

**Comment by joaoh1** [comment]
First of all, a resource pack's assets folder is completely different from .minecraft's. The resource path is mentioned on the config option so someone who wants to change it through a resource pack could do it by having a texture on that path. If you want to get the texture, open this mod's JAR file as a ZIP. If you want to change it, create a resource pack
