### ISSUE TITLE
Set default zoom when clicking zoom key

### ISSUE THREAD

**Issue by Minionguyjpro** [joaoh1/OkZoomer#27]
Add an config option how many you default zoom in when clicking the zoom key. Example: Like ive setted default zoom to x5, it automatticaly zooms x5 when clicking the zoom key. And if i set it to x50 zoom for default, then if i click the zoom key its auttomaticaly zoomed in x50.

**Comment by EnnuiL** [comment]
It's already an option, the "Zoom Divisor" option lets you change the default zoom
