### ISSUE TITLE
Mod is incompatible with Perspective Mod Redux

### ISSUE THREAD

**Issue by aestellic** [joaoh1/OkZoomer#28]
When pressing the zoom key (binded to c, no conflicts) on version okzoomer-5.0.0-beta.2+1.17.jar, the game instantly crashes, and I cannot load back into my worlds without deleting the mod. 

Here's the crash log: [https://gist.githubusercontent.com/natanfudge/5cf0e14a6802e6912104d38afc40c47d/raw/dabaca0fe462598aab443c03721bb23f9a48a539/crash.txt](url)

**Comment by EnnuiL** [comment]
There's a conflict with another mod who possibly also mixins into the Mouse class, however, I didn't find the mod itself; If possible, could you try to narrow down which mod crashes with Ok Zoomer?

**Comment by sschlester** [comment]
The crash occurs with Perspective Mod Redux.

Mods loaded:
  [✔️] fabric-api-0.36.0+1.17
  [✔️] okzoomer-5.0.0-beta.2+1.17
  [✔️] PerspectiveModRedux-1.17-0.0.5

Crash log: https://pastebin.com/ykQZksv9

**Comment by EnnuiL** [comment]
Looking at the source code, that mod uses a `@Redirect` mixin, which is incompatible with any other mod that touches the exact same area; There's nothing that I can do about the crash on Ok Zoomer's side, the only way to fix it is by avoiding the `@Redirect` and using a more compatible method to have the same result
