### ISSUE TITLE
OK Zoomer for Forge

### ISSUE THREAD

**Issue by Minionguyjpro** [joaoh1/OkZoomer#29]
Make OK Zoomer also available for Forge, because its an popular mod loader and so you can use it with mods.

**Comment by K0-RR** [comment]
https://github.com/Wurst-Imperium/WI-Zoom/issues/13

Let me say it again - if you need to use Forge then just use optifine or... one of the thousand other forge modloader zoom mods.

1-minute search results:
https://www.curseforge.com/minecraft/mc-mods/better-zoom
https://www.curseforge.com/minecraft/mc-mods/ezzoom
https://www.curseforge.com/minecraft/mc-mods/smoothfocus
https://www.curseforge.com/minecraft/mc-mods/simplezoom
https://www.curseforge.com/minecraft/mc-mods/forgezoom

**Comment by Minionguyjpro** [comment]
I posted this because thats other

**Comment by Minionguyjpro** [comment]
Like i dont wanna download like many mods

**Comment by Minionguyjpro** [comment]
I think it should be good to have an Forge version.

**Comment by K0-RR** [comment]
> Like i dont wanna download like many mods

Wat

**Comment by Minionguyjpro** [comment]
Like having everything in one is handyer.

**Comment by K0-RR** [comment]
Ok I tried a few times and I still don't get it
Why don't you download one of the already existing forge zoom mods instead of making port requests?

Also, what is keeping you with Forge instead of Fabric?

**Comment by Minionguyjpro** [comment]
Mods

**Comment by Minionguyjpro** [comment]
People would have like it if there was

**Comment by EnnuiL** [comment]
No, Ok Zoomer won't have an official port to Forge (although if someone else wants to port it, the MIT license allows them to do it).
If you want a zoom mod for Forge, there's [Smooth Focus](https://www.curseforge.com/minecraft/mc-mods/smoothfocus)
