### ISSUE TITLE
Zoom multiplier

### ISSUE THREAD

**Issue by Madis0** [joaoh1/OkZoomer#3]
It would be nice if we could also set the zoom multiplier - the number of divisor to change by scrolling, e.g 4 would increase 4.0 to 8.0, 12.0, 16.0 etc

**Comment by joaoh1** [comment]
This is something that I eventually want to add.

**Comment by joaoh1** [comment]
Added scroll steps and lesser scroll steps, they are the same thing as zoom multipliers
