### ISSUE TITLE
Crash when zooming

### ISSUE THREAD

**Issue by Boobies** [joaoh1/OkZoomer#31]
I am surprised not to see a ticket about this here, given how many people are complaining about this on the CurseForge page. Happens with 1.17. Given that it seems easy to reproduce by everyone (just hit the zoom hotkey) I didn't upload a crash log but let me know if you have trouble reproducing it yourself and I will upload one.

**Comment by atridey** [comment]
Are you using 1.17? The mod on CurseForge is for 1.16.5. The only way to get the 1.17 branch is to build it from here. I tried it and it works fine.

**Comment by EnnuiL** [comment]
I have absolutely no idea how these people are getting these crashes. I've already tested it with it and only Fabric API and the zoom key works properly; I'd think that there's a mod that everyone uses and it's crashing with it, but All Of Fabric 4 (which has a lot of mods and is for 1.17) has Ok Zoomer included and there were no problems with it.

My guess would be that people are accidentally downloading the 1.16 version of it (which is 4.0.0 and not 5.0.0) by pressing the "Download" button and somehow being able to have no crashes until pressing the zoom key, but the game crashes before loading. I've tested the 5.0.0-beta.1 (which was made for the latest 1.17 snapshot at the time), and it crashes when the world loads, which is not the crash that these people are experiencing.

I couldn't reproduce it and I still have no idea about the cause, but what I know if that if you download the mod through the sidebar, it should be absolutely fine; The Download button shouldn't be trusted and is currently downloading the 1.16 version of it:
![image](https://user-images.githubusercontent.com/85590273/124335220-07495a80-db70-11eb-9d60-ad84e1eef481.png)

**Comment by atridey** [comment]
That must be the reason why. I myself never saw the alternate downloads.

**Comment by EnnuiL** [comment]
Mystery solved, it was apparently the same issue as #28, where a crash happened when you pressed the zoom key with a specific mod installed; That mod has fixed the issue on their side
Anyway, if it's something else, then feel free to reopen this issue

**Comment by Boobies** [comment]
I cannot test right now but I can confirm that I did have this mod installed so it must've been my issue.
