### ISSUE TITLE
Crash when attempting to save a minimum zoom divisor that does not satisfy constraints for type DecimalSerializableType

### ISSUE THREAD

**Issue by ghost** [joaoh1/OkZoomer#33]
Upon trying to save a value (0.0) for the minimum zoom divisor that is lower than the minimum value allowed for its type (2.2250738585072014E-308), the game crashes. Based on the crash report, it *seems* that this issue could be solved by simply enforcing a reasonable minimum value before being allowed to save the mod's options.

Minecraft Version: 1.17.1

Relevant Mod Versions:
* Ok Zoomer - 5.0.0-beta.2+1.17
* Fabric API - 0.37.0+1.17
* Mod Menu - 2.0.3

Full mod list with respective versions can be found in the crash report.

Crash Report: [crash-2021-07-20_17.52.48-client.txt](https://github.com/EnnuiL/OkZoomer/files/6852057/crash-2021-07-20_17.52.48-client.txt)

**Comment by EnnuiL** [comment]
The next update fixes that issue by using a custom option widget in order to enforce a range limit to the input boxes
