### ISSUE TITLE
Suggestion: scale Scroll Step with Zoom Divisor

### ISSUE THREAD

**Issue by Hlebuw3k** [joaoh1/OkZoomer#36]
It becomes painfully slow to zoom in at a zoom divisor above 128. I think an easy implementation would be to multiply the scroll step by the zoom divisor, or even just add them together for the new scroll step value.

**Comment by EnnuiL** [comment]
Will be addressed by the implementation of #7

**Comment by EnnuiL** [comment]
Addressed by #7
