### ISSUE TITLE
Crashes when selecting in ModMenu.

### ISSUE THREAD

**Issue by PyICoder** [joaoh1/OkZoomer#4]
When I select OkZoomer in ModMenu it crashes
https://hst.sh/owidinifet.php

**Comment by joaoh1** [comment]
Ok Zoomer 3.x is not maintained anymore, the Ok Zoomer 4.0.0 alphas have fixed the issue, please use it instead (don't worry about bugs, it's quite stable now).

**Comment by shaneknysh** [comment]
For anyone else who came here with the same issue version 4.0.0 is not available on Curse Forge (as of 2020 Aug 07) and you have to download it from the [GitHub releases](https://github.com/joaoh1/OkZoomer/releases)

**Comment by joaoh1** [comment]
Yes, it is available on CurseForge, right below the 3.0.1 release

![Uploading 2020-08-07_20-06-51.png…]()

**Comment by shaneknysh** [comment]
I can't see it there
[curse forge files](https://imgur.com/a/l61brf5)

**Comment by joaoh1** [comment]
Looks like you will need to click the "View All" button in order to be able to see all the alphas, this will no longer be necessary once I manage to get a beta ready
![](https://i.imgur.com/tLhUn5h.png)
