### ISSUE TITLE
gradlew isn't executable

### ISSUE THREAD

**Issue by gen1dream** [joaoh1/OkZoomer#42]
the gradlew file has changed so its not executable 

`-rw-r--r-- 1 user user 8047 Oct 29 06:33 gradlew`

i did chmod +x now it works

`-rwxr-xr-x 1 user user 8047 Oct 29 06:33 gradlew`

**Comment by K0-RR** [comment]
It's not executable on most repositories

**Comment by gen1dream** [comment]
ok did not know that thanks
