### ISSUE TITLE
Mod needs a higher version of fabric than currently exists for 1.18

### ISSUE THREAD

**Issue by MBPpp** [joaoh1/OkZoomer#44]
To start off, I use MultiMC as my launcher so this might be a MultiMC thing, but I still want to say here that when I try to load it on fabric 1.18 it tells me I need version 0.37 of fabric when only 0.12 exists.

**Comment by K0-RR** [comment]
You are confusing Fabric Loader (the latest is 0.12.8) with Fabric API (newest is 0.43.1).

**Comment by K0-RR** [comment]
Fabric API modname is `fabric`. https://www.curseforge.com/minecraft/mc-mods/fabric-api/files

**Comment by MBPpp** [comment]
i'm so smart dude
