### ISSUE TITLE
Ok Zoomer 5.0.0-beta.3 has non-obvious crashes with MC 1.18.2

### ISSUE THREAD

**Issue by JasonHorkles** [joaoh1/OkZoomer#53]
Any time I try to hold an item that emits light with Iris also installed, such as a torch, the game crashes. This doesn't happen with only Ok Zoomer nor only with Iris, but only when both are installed. Iris claims it's likely an Ok Zoomer bug, but I'm willing to help figure out what exactly is causing it
https://bytebin.lucko.me/rYlIfcawh3
https://crashy.net/F0sd8yw1jtCzaVA3bFML

**Comment by EnnuiL** [comment]
The problem here is that LibZoomer is incompatible with Minecraft 1.18.2's tag changes. This has already been fixed, although an update to Ok Zoomer is still being worked on

**Comment by JasonHorkles** [comment]
Ah I see. Thank you!

**Comment by JustFoxx** [comment]
*waits for port for fabric 1.18.2 anyways*

**Comment by JCBOOMog** [comment]
Crashes when you open the inventory with no other mods installed

**Comment by EnnuiL** [comment]
Ok Zoomer 5.0.0-beta.4 is out, solving this issue
