### ISSUE TITLE
Ok Zoomer no longer registers keybind properly.

### ISSUE THREAD

**Issue by Kichura** [joaoh1/OkZoomer#55]
When using the latest [ok zoomer commit](https://github.com/EnnuiL/OkZoomer/commit/5198dce49dba70f87c9f4c3120cb6f2af25e5040) at time of writing this; the keybind for zooming no longer works and making changes to the config itself using mod menu will crash the client.

**Comment by EnnuiL** [comment]
It has already been fixed in-development; It was due to Fabric Loader somehow not reading the Jar-in-Jar'd QSL modules without having to declare them on fabric.mod.json's `depends`

**Comment by Kichura** [comment]
...yikes then.
