### ISSUE TITLE
Zoom keybindings no longer in settings menu.

### ISSUE THREAD

**Issue by Memphinstein** [joaoh1/OkZoomer#56]
Good evening,

On latest build #176 the keybindings are no longer in the settings menu.
Nothing in the logs to suggest something going wrong.
The default keybind of C does work, and modifications can be made through Mod Menu, so I don't beleve its a duplicaiton of Issue#55.

Tested on;
Minecraft 1.18.2
Fabric Loader 0.13.3
Fabric API 0.47.10
Mod Menu 3.1.0
Ok Zoomer 5.0.0-beta.4+1.18.2,github.176

Thank you for your time.

**Comment by EnnuiL** [comment]
Uh oh, looks like the key bind registration on the FAPI side has somehow failed; I'll quickly get a patched version ready

**Comment by EnnuiL** [comment]
Fixed on 5.0.0-beta.5!

**Comment by Memphinstein** [comment]
Cheers!

**Comment by Memphinstein** [comment]
Confirmed working, thank you very much!
