### ISSUE TITLE
[bug] Ok Zoomer crashes with CIT Resewn

### ISSUE THREAD

**Issue by DangerMage** [joaoh1/OkZoomer#58]
Mods: 
![image](https://user-images.githubusercontent.com/57050396/158039410-7e8a5e3b-b196-48c8-9a3c-8498786d5326.png)

[latest.log](https://github.com/EnnuiL/OkZoomer/files/8238735/latest.log)

log found in the log file

The game works if i turn off CIT Resewn or ok zoomer

**Comment by EnnuiL** [comment]
This issue has been solved on CIT Resewn's side, it's still pending an update release though
