### ISSUE TITLE
Incompatibility with Canvas

### ISSUE THREAD

**Issue by EdwardNottingham** [joaoh1/OkZoomer#6]
Hello, I love OK Zommer, so thank you so much for making it! 

However, I have run into a little issue while trying to use the Canvas rendering mod with it. I'm not sure if this is an issue with the Canvas plugin, or if it is an issue with OK Zoomer itself, but I thought I should inform you of the issue here nonetheless.

Regards,
Eddy

**Comment by joaoh1** [comment]
I have been playing with both Ok Zoomer and Canvas Renderer and I noticed no issues, what issue are you having specifically? I can't really help without knowing what's the issue.

**Comment by EdwardNottingham** [comment]
I spent some more time on this and have discovered that it is actually to do with conflicting control bindings. Sorry, I should have tried more things before reporting it to you. 

The issue is the following:

When using Sodium + OK Zoomer + Replay Mod everything works fine. Even with the shortcut "C" conflicting with the base game and Replay Mod, and the shortcut "V" conflicting with just Replay Mod. Everything still just worked.

However, when I switched over to Canvas Renderer + OK Zoomer + Replay Mod, it stopped registering the keystrokes with OK Zoomer. The only fix I found was to give OK Zoomer it's own bindings that are never used anywhere else.

I guess this isn't really an issue as users can expect to need to set independent keybindings, but maybe you have some insight into why this only happens with Canvas Renderer? I also let the Canvas devs know about the incompatibility, in case it is something on their end, so I'll let you know of any development on that ticket too.

Thank you for the time you spent testing this earlier, and sorry for bothering you with this not very important bug.

**Comment by joaoh1** [comment]
Thanks for going more in-depth on the issue, anyway, I wonder what could be causing this issue, it could possibly be one of Canvas' bundled dependencies? I will see what I can do in order to fix it, I probably can't do much, but if this mod is causing the issue, then I probably can fix it. And don't worry about if this bug is important or not, a minor annoyance can still be very annoying

**Comment by joaoh1** [comment]
Seems to not be related to Canvas according them but with Ok Zoomer not hijacking the vanilla's conflicting key, that will be solved in the next release with the trigger being migrated to the config file instead of relying of the non-existence of it

**Comment by EdwardNottingham** [comment]
Sounds like a good plan, I hope it works! :) Strange that Sodium didn't have that problem though!
