### ISSUE TITLE
Error: Game Crashed

### ISSUE THREAD

**Issue by Ivon365** [joaoh1/OkZoomer#63]
The game crashed whilst unexpected error
Error: java.lang.ClassCastException: class java.lang.Double cannot be cast to class net.minecraft.class_746 (java.lang.Double is in module java.base of loader 'bootstrap'; net.minecraft.class_746 is in unnamed module of loader net.fabricmc.loader.impl.launch.knot.KnotClassLoader @604c5de8)
Exit Code: -1

**Comment by Auzathoth** [comment]
I get this, but only if Better Third Person is also installed.

https://www.curseforge.com/minecraft/mc-mods/better-third-person/issues/28

**Comment by EnnuiL** [comment]
The log is way too tiny in order to determine a culprit, however, I believe that this might be a conflict between LibZoomer and an another mod; Those cases were probably solved by 5.0.0-beta.6, could you try it out?
