### ISSUE TITLE
Optifine connected textures

### ISSUE THREAD

**Issue by JCaldas-dev** [joaoh1/OkZoomer#66]
I'm using fabric 1.18.2 with a mod list with OkZoomer, Optifabric and the most recent version of Optifine. I´ve tested my mod list without the mod and it works perfectly.

okzoomer-5.0.0-beta.5+1.18.2 messes specifically with optifine's glass and glass pane connected glass textures. Optifine's grass blocks connected texture, for example, works as intended, although I never use this option. Only turned it on for testing.

**Comment by EnnuiL** [comment]
Due to OptiFine not being particularly mod-friendly, it and OptiFabric aren't supported. However, I believe it's the same underlying issue as #57. Could you check if this still happens on 5.0.0-beta.6?

**Comment by JCaldas-dev** [comment]
Unfortunately, glass textures remain separate with the most recent beta.

**Comment by FileOfName** [comment]
So while I've got no idea why this happens, I found a temporary fix: Simply by extracting Optifine's resource pack and enabling it manually, it worked. 
[Optifine_fix.zip](https://github.com/EnnuiL/OkZoomer/files/8500176/Optifine_fix.zip)

![image](https://user-images.githubusercontent.com/81038683/163682361-fae9d258-390d-4b02-b8ca-de16f1536632.png)

**Comment by JCaldas-dev** [comment]
This works perfectly, thanks a lot!

**Comment by EnnuiL** [comment]
Stale issue
