### ISSUE TITLE
Incompatibility with perspective mod redux

### ISSUE THREAD

**Issue by NotADinosaur** [joaoh1/OkZoomer#69]
With ok zoomer 5.0.0-beta 6, the game crashes upon joining a world or server. With 5.0.0-beta 5, it doesn't crash, but unfortunately that version is incompatible with continuity. I'm not sure whether the issue is caused by this mod or pmr though, because that mod hasn't been updated in quite a while. 
Log here: 
[latest.log](https://github.com/EnnuiL/OkZoomer/files/8468580/latest.log)

**Comment by EnnuiL** [comment]
I was about to declare a Dependency Snarl (more on that problem later, alongside a temporary solution), however, this seems like a simpler problem: I think that with Ok Zoomer declaring an explicit dependency on Fabric Loader 0.12, the improved Mixin local detection was activated on the mixin'd class; However, Perspective Mod Redux doesn't expect that expansion of possibilities, and so, it ends crashing;
This is probably something that Perspective Mod Redux will have to fix on its side; I tried to check its source code, however, yeah, it's gone. There isn't much that I can do about it
