### ISSUE TITLE
3-Way incompatibility with Charm and Origins

### ISSUE THREAD

**Issue by sisby-folk** [joaoh1/OkZoomer#73]
Minecraft 1.18.2 Fabric 0.13.3 FAPI 0.51.0
[latest.log](https://gist.github.com/sisby-folk/ee79fc2429511d9ef07249953920dc73)

![image](https://user-images.githubusercontent.com/55819817/164138452-10b00a91-1b5c-4f1a-9ece-9840a5423caa.png)

Issue specifically affects origins, preventing it from loading correctly (?)

Confirmed on a clean instance, doesn't occur when _either_ charm or zoomer is disabled (Which was bloody impossible to bisect).

[Issue on Origins](https://github.com/apace100/origins-fabric/issues/528)
[Issue on Charm](https://github.com/svenhjol/Charm/issues/770)

**Comment by Wahngrok** [comment]
Same issue with Origins + DeepslateCutting + OK Zoomer: https://github.com/apace100/origins-fabric/issues/523

**Comment by EnnuiL** [comment]
It should be fixed by the Quilt release of Ok Zoomer (5.0.0-beta.7); If not, please reopen
