### ISSUE TITLE
Included QSL libraries cause incompatible mods error if QSL is installed separately

### ISSUE THREAD

**Issue by Nolij** [joaoh1/OkZoomer#76]
As far as I can tell based on the error message, this mod appears to bundle some QSL libraries. Because of this, if QSL is installed separately by the user (or at least the latest version of QSL, beta 14 as of writing), an incompatible mods error is given and the game refuses to launch. This makes Fabric mods which require Fabric API are incompatible with Ok Zoomer.

Simple solution to this: stop bundling QSL. QSL will need to be installed manually for all users, but just about every mod in existence requires library mods nowadays, so I don't see the harm.

**Comment by EnnuiL** [comment]
QSL hasn't been bundled since 5.0.0-beta.7 (the first Quilt release); Assuming that you're on Quilt, updating this mod is all that is required in order to fix the issue
