### ISSUE TITLE
Ok Zoomer doesn't allow me to create new worlds/"Error in currently selected datapacks prevented the world from loading."

### ISSUE THREAD

**Issue by tonwu** [joaoh1/OkZoomer#80]
I'm not sure why but it might be interfering with other mods I have downloaded. I am using the beta 5 version for Minecraft.

![image_2022-06-15_205448712](https://user-images.githubusercontent.com/68622108/173987729-53ada93c-23b2-4e65-98c0-f03440557d44.png)

**Comment by theRookieCoder** [comment]
~~This screen shows up when you had mods that were used in a world, but now when you open them again you don't have that mod any more. Afaik this has nothing to do with OkZoomer, this is typically caused by world generation mods that use datapacks.~~ Read below

**Comment by EnnuiL** [comment]
No, that's probably indeed the fault of a now-broken version of Ok Zoomer; Once again, there isn't much that I can do about the issue, and yeah, the Fabric versions are unsupported
