### ISSUE TITLE
[Feature/Bug] somehow increase resolution of `tick` method for vignette calculations

### ISSUE THREAD

**Issue by nopeless** [joaoh1/OkZoomer#95]
I wanted to implement a fast, but noticable ease-out when zooming out

However, `public void tick` isn't called frequently enough for the zooming out vignette removal to be smooth. Can you guide me or change the tick method?

**Comment by EnnuiL** [comment]
The `tick` doesn't really need to run more often, we only have to lerp between our values, saving some calculations in the end;
This has been done for 5.0.0-beta.12+1.20, fixing the janky vignette transitions; I do, however, want to investigate different ways of doing the transitions in the future (after all, I want Ok Zoomer 6 to happen!)
