### ISSUE TITLE
Wrong file uploaded to Modrinth for v5.0.0-beta.13

### ISSUE THREAD

**Issue by unilock** [joaoh1/OkZoomer#97]
Looks like the `sources` jar was uploaded to Modrinth instead of the release jar :p

<img width="550" alt="image" src="https://github.com/EnnuiL/OkZoomer/assets/11802133/29c58678-f019-4add-afd1-786450db5911">

This, of course, leads to the game crashing with `Ok Zoomer requires version [0.7.0, ∞) of libzoomer, which is missing!`

**Comment by EnnuiL** [comment]
:woman_facepalming: 
fixed, thank you
